GET https://localhost:7224/api/product/
# For more info on HTTP files go to https://aka.ms/vs/httpfile
###
POST https://localhost:7224/api/product/
Content-type: application/json
{
  "name": "Touch Queue",
  "purchasePrice": 30000,
  "sellPrice": 120000.00
}
###

PUT https://localhost:7224/api/product/
Content-type: application/json
{
  "name": "Touch Queue",
  "purchasePrice": 30000,
  "sellPrice": 120000.00
}
###

DELETE https://localhost:7224/api/product/